# Generated by Django 5.1.2 on 2024-11-02 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_participante', models.CharField(max_length=200)),
                ('email_participante', models.EmailField(max_length=254)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.evento')),
            ],
            options={
                'unique_together': {('evento', 'email_participante')},
            },
        ),
    ]
