# Generated by Django 5.1.2 on 2024-11-09 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_inscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Fim')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('location', models.CharField(max_length=255, verbose_name='Local')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizador_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
        ),
    ]
