# Generated by Django 5.1.2 on 2024-11-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
